special_tokens:
    "PAD": 0
    "START": 2
    "END": 1
    "UNK": 3
    "SEP": 4
    "(": 10
    ")": 11
    "e": 13
    "p": 14
    "i": 15
    "u": 16
    "n": 17
    "1p": 18
    "2p": 19
    "3p": 20
    "4p": 21
    "1e": 22
    "2e": 23
    "3e": 24
    "4e": 25
    "5e": 26
    "with": 27
offset: 100
# ans_len: 32
ans_len: 64
qry_len: 128
act_len: 32
act_max_var: 16
